import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";

const Login = () => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  }, []);

  // console.log(loading);

  if (loading) {
    return (
      <div className={`flex overflow-hidden h-screen bg-hostinger-Dark-blue/5 w-screen justify-center items-center`}>
        <Head>
          <title>Hostinger</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="https://res.cloudinary.com/dfk5jbk5r/image/upload/v1663594437/Hostinger/image_11_1_fgff04.svg" />
        </Head>
        <div className="animate-test overflow-hidden relative w-full h-full flex justify-center items-center">
          <Image
            src="https://res.cloudinary.com/dfk5jbk5r/image/upload/v1663856004/Hostinger/logo-homepage2020-f9c79137d7_li99ai.svg"
            alt="loader"
            width={200}
            height={40}
            objectFit="contain"
            layout="fill"
          />
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-center text-hostinger-Dark-blue font-['Nunito'] max-w-[95rem] bg-white mx-auto">
      <Head>
        <title>Login | Choose Hostinger and Host Your Site for Only ₹129.00/mo</title>
        <meta name="description" content="Choose Hostinger and Host Your Site for Only ₹129.00/mo" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/dfk5jbk5r/image/upload/v1663594437/Hostinger/image_11_1_fgff04.svg"
        />
      </Head>
      <motion.div initial={{
              x: -100,
            }}
            transition={{
              duration: 1,
            }}
            whileInView={{ x: 0 }}
            viewport={{ once: true }}  className="lg:w-1/2 max-w-md mx-auto px-2 flex flex-col items-center space-y-6 2xl:space-y-8 py-10">
        <h1 className="text-3xl font-bold mx-auto text-center">LOG IN</h1>
        {/* Buttons */}
        <div className="max-w-md min-w-[20rem] md:min-w-[28rem] flex flex-col space-y-6 2xl:space-y-8 mx-auto">
          <button className="bg-hostinger-Dark-blue/10 active:scale-90 transition transform ease-out duration-500 flex items-center justify-center space-x-5 w-full rounded-xl px-10 py-4">
            <Image
              src="https://res.cloudinary.com/dfk5jbk5r/image/upload/v1663858978/Hostinger/image_20_uba3wc.svg"
              width={25}
              height={25}
              alt="Google"
            />
            <span className="font-bold uppercase">Google</span>
          </button>
          <button className="bg-hostinger-Dark-blue/10 active:scale-90 transition transform ease-out duration-500 flex items-center justify-center space-x-5 w-full rounded-xl px-10 py-4">
            <Image
              src="https://res.cloudinary.com/dfk5jbk5r/image/upload/v1663858614/Hostinger/icons8-facebook-480_1_vsoryt.svg"
              width={25}
              height={25}
              alt="Facebook"
            />
            <span className="font-bold uppercase">Facebook</span>
          </button>
          {/* OR */}
          <div className="flex items-center justify-between">
            <div className="h-[2px] w-5/12 rounded-full bg-hostinger-Dark-blue/10" />
            <span className="text-hostinger-Dark-blue/40  font-medium text-lg">
              or
            </span>
            <div className="h-[2px] w-5/12 rounded-full bg-hostinger-Dark-blue/10" />
          </div>
          {/* Form */}
          <div className="flex flex-col space-y-6 2xl:space-y-8">
            <input
              type="text"
              placeholder="Email"
              className="placeholder:text-hostinger-Dark-blue/60 text-lg bg-hostinger-Dark-blue/10 outline-none duration-500 flex items-center justify-center space-x-5 w-full rounded-xl px-10 py-3.5"
            />
            <input
              type="text"
              placeholder="Password"
              className="placeholder:text-hostinger-Dark-blue/60 text-lg bg-hostinger-Dark-blue/10 outline-none duration-500 flex items-center justify-center space-x-5 w-full rounded-xl px-10 py-3.5"
            />
            <button className="bg-hostinger-pink text-white active:scale-90 transition transform ease-out duration-500 flex items-center justify-center space-x-5 w-full rounded-xl px-10 py-4">
              <span className="font-bold text-lg">Login</span>
            </button>
          </div>
        </div>
      </motion.div>
      <div className="hidden lg:block min-h-screen w-1/2 bg-cover bg-right bg-[url('https://res.cloudinary.com/dfk5jbk5r/image/upload/v1663592601/Hostinger/anas-alshanti-feXpdV001o4-unsplash_jcqx9w.jpg')]"></div>
    </div>
  );
};

export default Login;
